version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    platform: linux/x86_64
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - napdb-volume:/var/lib/postgresql/data

volumes:
  napdb-volume:
    driver: local
